### ISSUE TITLE
Equipment Advice

### ISSUE THREAD

**Issue by SamBailey6194** [SamBailey6194/photo-guides#1]
**User Story:**
As a beginner photographer, I want to understand what type of camera body and lens I should get to start so that I have the right equipment for my level of photography and at a small cost.

**Acceptance Criteria:**

- [x] Provide a section that explains different camera bodies.
- [x] Provide a section explaining different types of camera lenses.
- [x] Provide price points for different camera bodies and lenses.

**Tasks:**

- [x] Have a HTML page outlining different equipment
- [x] On the HTML page have a 2 sections, 1 for camera bodies and 1 for lenses
- [x] In each section have 3 price points, entry level, intermediate level and professional level
- [x] Use CSS to ensure the style is appealing and it is responsive to different sizes

**Priority:**
Must-Have
