### ISSUE TITLE
Advice on Camera Lenses

### ISSUE THREAD

**Issue by SamBailey6194** [SamBailey6194/photo-guides#2]
**User Story:**
As a owner of a DSLR camera and 1 lens, I want to know what other lens types are out there so that I can expand my equipment appropriately.

**Acceptance Criteria:**

- [x] Provide an explanation on different lenses and their uses
- [x] Explain what type of lenses people should have and why

**Tasks:**

- [x] HTML Section explaining different lenses and their use cases
- [x] HTML Section explaining what lenses each photographer should have in their kit
- [x] Use CSS to ensure the style is appealing and it is responsive to different sizes

**Priority:**
Must-Have
