### ISSUE TITLE
Advice for Videos

### ISSUE THREAD

**Issue by SamBailey6194** [SamBailey6194/photo-guides#3]
**User Story:**
As a amateur photographer, I want to expand and do videos as well and need advice on what camera body type I need to achieve this so that I can have high quality photos and videos on the same camera and switch modes easily.

**Acceptance Criteria:**

- [x] Explain what camera bodies achieve both high quality photos and videos
- [ ] Have different price points and the benefits and cons of different price points

**Tasks:**

- [ ] HTML Section with a comparison list for which camera bodies do photos and videos and what quality they do them at
- [x] HTML section outlining the price points
- [x] Use CSS to ensure the style is appealing and it is responsive to different sizes

**Priority:**
Could-Have
