### ISSUE TITLE
Teaching Settings

### ISSUE THREAD

**Issue by SamBailey6194** [SamBailey6194/photo-guides#4]
**User Story:**
As a beginner photographer, I would like to understand how to use the settings on the camera better so that I can improve the quality of my photos.

**Acceptance Criteria:**

- [x] Provide an explanation of different settings on a camera
- [x] Provide a tutorial to explain how to use the settings

**Tasks:**

- [x] HTML Page with the explanation and tutorial on it
- [x] HTML Section explaining the different settings on a camera
- [x] HTML Section using images to illustrate and teach how to use the settings for different situations
- [x] Use CSS to ensure the style is appealing and it is responsive to different sizes

**Priority:**
Must-Have
