### ISSUE TITLE
Badly Lit Photos

### ISSUE THREAD

**Issue by SamBailey6194** [SamBailey6194/photo-guides#5]
**User Story**
As the family photographer, I would like to understand why my photos regularly are badly lit so that I can ensure I am using the right settings to light my photos best.

**Acceptance Criteria:**

- [x] Provide an explanation of different settings on a camera and how they affect the light
- [x] Provide a tutorial to explain how to use the settings focusing on light

**Tasks:**

- [x] HTML Page with the explanation and tutorial on it
- [x] HTML Section explaining the different settings on a camera and how they affect the light
- [x] HTML Section using images to illustrate and teach how to use the settings to affect the lighting
- [x] Use CSS to ensure the style is appealing and it is responsive to different sizes

**Priority:**
Must-Have
