### ISSUE TITLE
History of Photography

### ISSUE THREAD

**Issue by SamBailey6194** [SamBailey6194/photo-guides#6]
**User Story**
As a lover of history, I would like to knbow the history of photography so that I can expand my knowledge on the history of various topics.

**Acceptance Criteria:**

- [x] Provide a timeline explaining the history of photography
- [x] Provide an understanding as to what started photography
- [x] Explain cameras through the years

**Tasks:**

- [x] HTML Page about the history of photography
- [x] HTML Section within the page with a styled timeline detailing the history of photography
- [x] The timeline to include the types of cameras throughout the years
- [x] Use CSS to ensure the style is appealing and it is responsive to different sizes

**Priority:**
Should-Have
