### ISSUE TITLE
Famous Photographers

### ISSUE THREAD

**Issue by SamBailey6194** [SamBailey6194/photo-guides#7]
**User Story**
As a budding photographer, I would like to know some famous photographers and their style of photography so that I can look to them for inspiration in my own work.

**Acceptance Criteria:**

- [x] Provide a list of famous photographers and links to their portfolios
- [x] Explain their style of photography

**Tasks:**

- [x] HTML Section under the history with 3 famous photographers from different eras
- [ ] In the section explain their style and provide links that open in a new tab/window of their portfolio
- [x] Use CSS to ensure the style is appealing and it is responsive to different sizes

**Priority:**
Should-Have
